// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

// Controllers will be imported automatically when referenced in your application
// Add any additional controller imports manually here if needed
import PromptFormController from "./prompt_form_controller"
application.register("prompt-form", PromptFormController)

// Uncomment to add additional controllers
// import ChatController from "./chat_controller"
// application.register("chat", ChatController)
