// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

//import { application } from "./application"

//import LegacyJsController from "./legacy_js_controller"
//application.register("legacy-js", LegacyJsController)
