// Engine default settings and TMDB demo detection — ported from Angular settingsSvc.
// Used by the case creation wizard to supply defaults for each search engine type.

export const defaultSettings = {
  solr: {
    queryParams: "q=#$query##\n&tie=1.0",
    escapeQuery: true,
    customHeaders: "",
    apiMethod: "JSONP",
    fieldSpec: "id:id",
    idField: "id",
    titleField: "",
    additionalFields: [],
    numberOfRows: 10,
    searchEngine: "solr",
    insecureSearchUrl: "http://quepid-solr.dev.o19s.com:8985/solr/tmdb/select",
    secureSearchUrl: "https://quepid-solr.dev.o19s.com/solr/tmdb/select",
    urlFormat: "http(s?)://yourdomain.com:8983/<index>/select",
    proxyRequests: false,
    basicAuthCredential: "",
  },
  es: {
    queryParams: [
      "{",
      '  "query": {',
      '    "multi_match": {',
      '      "query": "#$query##",',
      '      "type": "best_fields",',
      '      "fields": ["REPLACE_ME"]',
      "    }",
      "  }",
      "}",
    ].join("\n"),
    escapeQuery: true,
    apiMethod: "POST",
    customHeaders: "",
    fieldSpec: "id:_id",
    idField: "_id",
    titleField: "",
    additionalFields: [],
    numberOfRows: 10,
    searchEngine: "es",
    searchUrl: "http://quepid-elasticsearch.dev.o19s.com:9206/tmdb/_search",
    urlFormat: "http(s?)://yourdomain.com:9200/<index>/_search",
    proxyRequests: false,
    basicAuthCredential: "",
  },
  os: {
    queryParams: [
      "{",
      '  "query": {',
      '    "multi_match": {',
      '      "query": "#$query##",',
      '      "fields": ["*"]',
      "    }",
      "  }",
      "}",
    ].join("\n"),
    escapeQuery: true,
    apiMethod: "POST",
    customHeaders: "",
    fieldSpec: "id:_id",
    idField: "_id",
    titleField: "",
    additionalFields: [],
    numberOfRows: 10,
    searchEngine: "os",
    searchUrl: "https://quepid-opensearch.dev.o19s.com:9000/tmdb/_search",
    urlFormat: "http(s?)://yourdomain.com:9200/<index>/_search",
    proxyRequests: false,
    basicAuthCredential: "reader:reader",
  },
  vectara: {
    queryParams: [
      "{",
      '  "query": [',
      "     {",
      '       "query": "#$query##",',
      '       "start": 0,',
      '       "numResults": 10,',
      '       "corpusKey": [{',
      '          "corpusId": 1,',
      '          "lexicalInterpolationConfig": {',
      '            "lambda": 0.025',
      "          },",
      '          "dim": []',
      "       }]",
      "     }",
      "  ]",
      "}",
    ].join("\n"),
    escapeQuery: true,
    apiMethod: "POST",
    customHeaders: [
      "{",
      '  "customer-id": "YOUR_CUSTOMER_ID",',
      '  "x-api-key": "YOUR_API_KEY"',
      "}",
    ].join("\n"),
    fieldSpec: "id:id",
    idField: "id",
    titleField: "title",
    additionalFields: [],
    numberOfRows: 10,
    searchEngine: "vectara",
    searchUrl: "https://api.vectara.io/v1/query",
    urlFormat: "https://api.vectara.io/v1/query",
    proxyRequests: false,
    basicAuthCredential: "",
  },
  algolia: {
    queryParams: [
      "{",
      '"query": "#$query##",',
      '"clickAnalytics": true,',
      '"getRankingInfo": true,',
      '"restrictSearchableAttributes": [],',
      '"enableReRanking": true,',
      '"attributesToHighlight": [],',
      '"page": 0,',
      '"hitsPerPage": 10',
      "}",
    ].join("\n"),
    escapeQuery: true,
    apiMethod: "POST",
    customHeaders: [
      "{",
      '  "x-algolia-application-id": "OKF83BFQS4",',
      '  "x-algolia-api-key": "2ee1381ed11d3fe70b60605b1e2cd3f4"',
      "}",
    ].join("\n"),
    idField: "objectID",
    titleField: "title",
    additionalFields: ["overview", "cast", "thumb:poster_path"],
    numberOfRows: 10,
    searchEngine: "algolia",
    searchUrl: "https://OKF83BFQS4-dsn.algolia.net/1/indexes/movies_demo_quepid/query",
    urlFormat: "https://<APPLICATION-ID>-dsn.algolia.net/1/indexes/<index>/query",
    proxyRequests: true,
    basicAuthCredential: "",
  },
  static: {
    queryParams: "q=#$query##",
    escapeQuery: true,
    apiMethod: "GET",
    customHeaders: "",
    fieldSpec: "id:id",
    idField: "id",
    titleField: "",
    additionalFields: [],
    numberOfRows: 10,
    searchEngine: "static",
    proxyRequests: false,
  },
  searchapi: {
    escapeQuery: true,
    apiMethod: "POST",
    customHeaders: "",
    fieldSpec: null,
    idField: null,
    titleField: null,
    additionalFields: [],
    numberOfRows: 10,
    searchEngine: "searchapi",
    searchUrl: "https://example.com/api/search",
    urlFormat: null,
    proxyRequests: true,
    mapperCode: [
      "numberOfResultsMapper = function(data){",
      "  return data.length;",
      "};",
      "",
      "docsMapper = function(data){",
      "  let docs = [];",
      "  for (let doc of data) {",
      "    docs.push ({",
      "      id: doc.publication_id,",
      "      title: doc.title,",
      "    });",
      "  }",
      "  return docs;",
      "};",
    ].join("\n"),
  },
}

export const tmdbSettings = {
  solr: {
    queryParams: [
      "q=#$query##",
      "&defType=edismax",
      "&qf=text_all",
      "&pf=title",
      "&tie=1.0",
      "&bf=vote_average",
    ].join("\n"),
    escapeQuery: true,
    customHeaders: "",
    apiMethod: "JSONP",
    fieldSpec: "id:id, title:title",
    idField: "id",
    titleField: "title",
    additionalFields: ["overview", "cast", "thumb:poster_path"],
    numberOfRows: 10,
    searchEngine: "solr",
    insecureSearchUrl: "http://quepid-solr.dev.o19s.com:8985/solr/tmdb/select",
    secureSearchUrl: "https://quepid-solr.dev.o19s.com/solr/tmdb/select",
    urlFormat: "http(s?)://yourdomain.com:8983/<index>/select",
    proxyRequests: false,
    basicAuthCredential: "",
  },
  es: {
    queryParams: [
      "{",
      '  "query": {',
      '    "multi_match": {',
      '      "query": "#$query##",',
      '      "type": "best_fields",',
      '      "fields": [',
      '        "title^10",',
      '        "overview",',
      '        "cast"',
      "      ]",
      "    }",
      "  }",
      "}",
    ].join("\n"),
    escapeQuery: true,
    apiMethod: "POST",
    customHeaders: "",
    fieldSpec: "id:_id, title:title",
    idField: "_id",
    titleField: "title",
    additionalFields: ["overview", "cast", "thumb:poster_path"],
    numberOfRows: 10,
    searchEngine: "es",
    searchUrl: "http://quepid-elasticsearch.dev.o19s.com:9206/tmdb/_search",
    urlFormat: "http(s?)://yourdomain.com:9200/<index>/_search",
    proxyRequests: false,
    basicAuthCredential: "",
  },
  os: {
    queryParams: [
      "{",
      '  "query": {',
      '    "multi_match": {',
      '      "query": "#$query##",',
      '      "type": "best_fields",',
      '      "fields": [',
      '        "title^10",',
      '        "overview",',
      '        "cast"',
      "      ]",
      "    }",
      "  }",
      "}",
    ].join("\n"),
    escapeQuery: true,
    apiMethod: "POST",
    fieldSpec: "id:_id, title:title",
    idField: "_id",
    titleField: "title",
    additionalFields: ["overview", "cast", "thumb:poster_path"],
    numberOfRows: 10,
    searchEngine: "os",
    searchUrl: "https://quepid-opensearch.dev.o19s.com:9000/tmdb/_search",
    urlFormat: "http(s?)://yourdomain.com:9200/<index>/_search",
    customHeaders: "",
    proxyRequests: false,
    basicAuthCredential: "reader:reader",
  },
}

// Detect whether the user is pointing at one of the known TMDB demo endpoints.
export function isDemoUrl(searchEngine, searchUrl) {
  if (!tmdbSettings[searchEngine]) return false

  if (searchEngine === "solr") {
    if (!searchUrl) return true // null/undefined → default demo
    return (
      searchUrl === tmdbSettings.solr.insecureSearchUrl ||
      searchUrl === tmdbSettings.solr.secureSearchUrl
    )
  }

  return searchUrl === tmdbSettings[searchEngine].searchUrl
}

// Return the right defaults: TMDB-tuned when targeting a demo endpoint,
// generic engine defaults otherwise.
export function pickSettings(searchEngine, searchUrl) {
  if (isDemoUrl(searchEngine, searchUrl)) {
    return structuredClone(tmdbSettings[searchEngine])
  }
  return structuredClone(defaultSettings[searchEngine] || {})
}
