# Async adapter only works within the same process, so for manually triggering cable updates from a console,
# and seeing results in the browser, you must do so from the web console (running inside the dev process),
# not a terminal started via bin/rails console! Add "console" to any action or any ERB template view
# to make the web console appear.
development:
  #adapter: async
  adapter: solid_cable
  
  # We are using the primary database not a separate database
  #connects_to:
  #  database:
  #    writing: cable
  polling_interval: <%= ENV.fetch("SOLID_CABLE_POLLING", '0.1.seconds') %>
  message_retention: 1.hour
  silence_polling: true

test:
  adapter: test

production:
  adapter: solid_cable
  
  # We are using the primary database not a separate database
  #connects_to:
  #  database:
  #    writing: cable
  polling_interval: <%= ENV.fetch("SOLID_CABLE_POLLING", '0.1.seconds') %>
  message_retention: 1.hour
  silence_polling: true
