development:
  nightly_run_cases_command:
    class: EnqueueRunNightlyCasesJob
    schedule: every day at 1 am
    
  nightly_run_blazer_checks_command:
    class: RunBlazerChecksJob
    schedule: every hour


production:
  nightly_run_cases_command:
    class: EnqueueRunNightlyCasesJob
    schedule: every day at 1 am
    
  nightly_run_blazer_checks_command:
    class: RunBlazerChecksJob
    schedule: every day at 7 am
