development:
  nightly_jobs_command:
    command: "Case.enqueue_nightly_query_runner_jobs"    
    priority: 2
    #schedule: at 5am every day
    schedule: every minute

  # periodic_cleanup:
  #   class: QueryRunnerJob
  #   queue: bulk_processing
  #   args: [ 'gid://quepid/Case/10', 'gid://quepid/Try/87'  ]
  #   schedule: every minute


production:
  nightly_jobs_command:
    command: "Case.enqueue_nightly_query_runner_jobs"
    priority: 2
    #schedule: at 5am every day
    #schedule: every day at 8pm
    schedule: every hour
    
  nightly_jobs_command2:
    class: EnqueueNightlyQueryRunnerJobs
    queue: background
    schedule: every minute
 

  # periodic_cleanup:
  #   class: QueryRunnerJob
  #   queue: bulk_processing
  #   args: [ 'gid://quepid/Case/10', 'gid://quepid/Try/87'  ]
  #   schedule: every minute
