development:
  nightly_jobs_command:
    class: EnqueueNightlyQueryRunnerJob
    schedule: every hour

  # periodic_cleanup:
  #   class: QueryRunnerJob
  #   queue: bulk_processing
  #   args: [ 'gid://quepid/Case/10', 'gid://quepid/Try/87'  ]
  #   schedule: every minute


production:
  nightly_jobs_command:
    class: EnqueueNightlyQueryRunnerJob
    schedule: every hour
 

  # periodic_cleanup:
  #   class: QueryRunnerJob
  #   queue: bulk_processing
  #   args: [ 'gid://quepid/Case/10', 'gid://quepid/Try/87'  ]
  #   schedule: every minute
